name: gcp-hosting-signalr-server.yml
on:
  push:
    branches:
      - main
    paths:
      - "ChatServer/**"

permissions: 
  id-token: write 
  contents: read
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ChatServer
        
    steps:
      - uses: actions/checkout@v4
          
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
          audience: ${{ secrets.WIF_PROVIDER }}